In [1]:
import numpy as np

In [2]:
prices = np.array([100, 120, 150, 130])

print(prices)

[100 120 150 130]


In [3]:
numbers = np.arange(1, 11)

print(numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
prices = np.array([100, 120, 150, 130])

print(type(prices))
print(prices.dtype)

<class 'numpy.ndarray'>
int64


In [5]:
prices = np.array([100, 120, 150, 130, 170])

print(prices[0])
print(prices[2])
print(prices[-1])

100
150
170


In [6]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])

print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])
print(arr[-1])
print(arr[-2])
print(arr[5])
print(arr[6])
print(arr[7])

10
20
30
40
50
100
90
60
70
80


In [7]:
arr = np.array([10,20,30,40,50,60,70,80])

print(arr[0:3])
print(arr[2:6])
print(arr[:4])
print(arr[4:])

[10 20 30]
[30 40 50 60]
[10 20 30 40]
[50 60 70 80]


In [8]:
prices = np.array([100,120,150,130])

new_prices = prices + 10

print(new_prices)

[110 130 160 140]


In [9]:
prices = np.array([100,120,150,130])

print(prices * 2)

[200 240 300 260]


In [10]:
prices = np.array([100, 105, 110, 108, 120])

In [11]:
returns = (prices[1:] - prices[:-1]) / prices[:-1]

print(returns)

[ 0.05        0.04761905 -0.01818182  0.11111111]


In [12]:
returns_percent = returns * 100

print(returns_percent)

[ 5.          4.76190476 -1.81818182 11.11111111]


In [13]:
prices = [100,105,110,108,120]

returns = []

for i in range(1, len(prices)):
    
    r = (prices[i] - prices[i-1]) / prices[i-1]
    
    returns.append(r)

print(returns)

[0.05, 0.047619047619047616, -0.01818181818181818, 0.1111111111111111]


In [14]:
import numpy as np

prices = np.array([100,105,110,108,120])

returns = (prices[1:] - prices[:-1]) / prices[:-1]

print(returns)

[ 0.05        0.04761905 -0.01818182  0.11111111]


In [15]:
%timeit [(prices[i] - prices[i-1]) / prices[i-1] for i in range(1, len(prices))]

1.88 μs ± 131 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [16]:
prices = np.arange(1,100000)

%timeit (prices[1:] - prices[:-1]) / prices[:-1]

848 μs ± 58.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
