In [2]:
import numpy as np

In [3]:
np.random.seed(42)

In [4]:
daily_returns = np.random.normal(
    loc=0.001,
    scale=0.02,
    size=1000
)

print(daily_returns[:10])

[ 0.01093428 -0.00176529  0.01395377  0.0314606  -0.00368307 -0.00368274
  0.03258426  0.01634869 -0.00838949  0.0118512 ]


In [5]:
print(np.mean(daily_returns))

0.0013866411164465107


In [6]:
print(np.std(daily_returns))

0.019574524154947086


In [7]:
print("25th:", np.percentile(daily_returns,25))

print("50th:", np.percentile(daily_returns,50))

print("75th:", np.percentile(daily_returns,75))

25th: -0.011951806109247032
50th: 0.001506012244697765
75th: 0.0139588775094586


In [8]:
start_price = 100

In [9]:
price_series = start_price * np.cumprod(
    1 + daily_returns
)

print(price_series[:10])

[101.09342831 100.91496949 102.32311384 105.5422601  105.15354083
 104.76628777 108.18001935 109.94862144 109.02620883 110.31830034]


In [10]:
print("Average Price:",
      np.mean(price_series))

print("Highest Price:",
      np.max(price_series))

print("Lowest Price:",
      np.min(price_series))

print("Final Price:",
      price_series[-1])

Average Price: 159.81453939582863
Highest Price: 379.8497588860007
Lowest Price: 82.17958997086465
Final Price: 330.2927737383623


In [11]:
data = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(data)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [12]:
print(np.sum(data, axis=0))

[120 150 180]


In [13]:
print(np.sum(data, axis=1))

[ 60 150 240]


In [14]:
A = np.array([
    [1,2],
    [3,4]
])

print(np.linalg.det(A))

print(np.linalg.inv(A))

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]
